// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigFormat int32

const (
	ConfigFormat_PLAIN ConfigFormat = 0
	ConfigFormat_JSON  ConfigFormat = 1
	ConfigFormat_YAML  ConfigFormat = 2
)

// Enum value maps for ConfigFormat.
var (
	ConfigFormat_name = map[int32]string{
		0: "PLAIN",
		1: "JSON",
		2: "YAML",
	}
	ConfigFormat_value = map[string]int32{
		"PLAIN": 0,
		"JSON":  1,
		"YAML":  2,
	}
)

func (x ConfigFormat) Enum() *ConfigFormat {
	p := new(ConfigFormat)
	*p = x
	return p
}

func (x ConfigFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_service_proto_enumTypes[0].Descriptor()
}

func (ConfigFormat) Type() protoreflect.EnumType {
	return &file_proto_service_proto_enumTypes[0]
}

func (x ConfigFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigFormat.Descriptor instead.
func (ConfigFormat) EnumDescriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

type Backend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *string                `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Version       *string                `protobuf:"bytes,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Inbounds      []*Inbound             `protobuf:"bytes,4,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *Backend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Backend) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Backend) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *Backend) GetInbounds() []*Inbound {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

type BackendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backends      []*Backend             `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendsResponse) Reset() {
	*x = BackendsResponse{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendsResponse) ProtoMessage() {}

func (x *BackendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendsResponse.ProtoReflect.Descriptor instead.
func (*BackendsResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *BackendsResponse) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

type Inbound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Config        *string                `protobuf:"bytes,2,opt,name=config,proto3,oneof" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inbound) Reset() {
	*x = Inbound{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inbound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inbound) ProtoMessage() {}

func (x *Inbound) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inbound.ProtoReflect.Descriptor instead.
func (*Inbound) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *Inbound) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Inbound) GetConfig() string {
	if x != nil && x.Config != nil {
		return *x.Config
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type UserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Inbounds      []*Inbound             `protobuf:"bytes,2,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *UserData) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserData) GetInbounds() []*Inbound {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

type UsersData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsersData     []*UserData            `protobuf:"bytes,1,rep,name=users_data,json=usersData,proto3" json:"users_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersData) Reset() {
	*x = UsersData{}
	mi := &file_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersData) ProtoMessage() {}

func (x *UsersData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersData.ProtoReflect.Descriptor instead.
func (*UsersData) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *UsersData) GetUsersData() []*UserData {
	if x != nil {
		return x.UsersData
	}
	return nil
}

type UsersStats struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UsersStats    []*UsersStats_UserStats `protobuf:"bytes,1,rep,name=users_stats,json=usersStats,proto3" json:"users_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersStats) Reset() {
	*x = UsersStats{}
	mi := &file_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersStats) ProtoMessage() {}

func (x *UsersStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersStats.ProtoReflect.Descriptor instead.
func (*UsersStats) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *UsersStats) GetUsersStats() []*UsersStats_UserStats {
	if x != nil {
		return x.UsersStats
	}
	return nil
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_proto_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{8}
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type BackendConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration string                 `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	ConfigFormat  ConfigFormat           `protobuf:"varint,2,opt,name=config_format,json=configFormat,proto3,enum=api.ConfigFormat" json:"config_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendConfig) Reset() {
	*x = BackendConfig{}
	mi := &file_proto_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendConfig) ProtoMessage() {}

func (x *BackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendConfig.ProtoReflect.Descriptor instead.
func (*BackendConfig) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{9}
}

func (x *BackendConfig) GetConfiguration() string {
	if x != nil {
		return x.Configuration
	}
	return ""
}

func (x *BackendConfig) GetConfigFormat() ConfigFormat {
	if x != nil {
		return x.ConfigFormat
	}
	return ConfigFormat_PLAIN
}

type BackendLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendName   string                 `protobuf:"bytes,1,opt,name=backend_name,json=backendName,proto3" json:"backend_name,omitempty"`
	IncludeBuffer bool                   `protobuf:"varint,2,opt,name=include_buffer,json=includeBuffer,proto3" json:"include_buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendLogsRequest) Reset() {
	*x = BackendLogsRequest{}
	mi := &file_proto_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendLogsRequest) ProtoMessage() {}

func (x *BackendLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendLogsRequest.ProtoReflect.Descriptor instead.
func (*BackendLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *BackendLogsRequest) GetBackendName() string {
	if x != nil {
		return x.BackendName
	}
	return ""
}

func (x *BackendLogsRequest) GetIncludeBuffer() bool {
	if x != nil {
		return x.IncludeBuffer
	}
	return false
}

type RestartBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendName   string                 `protobuf:"bytes,1,opt,name=backend_name,json=backendName,proto3" json:"backend_name,omitempty"`
	Config        *BackendConfig         `protobuf:"bytes,2,opt,name=config,proto3,oneof" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartBackendRequest) Reset() {
	*x = RestartBackendRequest{}
	mi := &file_proto_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartBackendRequest) ProtoMessage() {}

func (x *RestartBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartBackendRequest.ProtoReflect.Descriptor instead.
func (*RestartBackendRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{11}
}

func (x *RestartBackendRequest) GetBackendName() string {
	if x != nil {
		return x.BackendName
	}
	return ""
}

func (x *RestartBackendRequest) GetConfig() *BackendConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type BackendStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendStats) Reset() {
	*x = BackendStats{}
	mi := &file_proto_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendStats) ProtoMessage() {}

func (x *BackendStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendStats.ProtoReflect.Descriptor instead.
func (*BackendStats) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{12}
}

func (x *BackendStats) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

type UsersStats_UserStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Usage         uint64                 `protobuf:"varint,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersStats_UserStats) Reset() {
	*x = UsersStats_UserStats{}
	mi := &file_proto_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersStats_UserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersStats_UserStats) ProtoMessage() {}

func (x *UsersStats_UserStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersStats_UserStats.ProtoReflect.Descriptor instead.
func (*UsersStats_UserStats) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{7, 0}
}

func (x *UsersStats_UserStats) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UsersStats_UserStats) GetUsage() uint64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\x03api\"\a\n" +
	"\x05Empty\"\x94\x01\n" +
	"\aBackend\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tH\x00R\x04type\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\tH\x01R\aversion\x88\x01\x01\x12(\n" +
	"\binbounds\x18\x04 \x03(\v2\f.api.InboundR\binboundsB\a\n" +
	"\x05_typeB\n" +
	"\n" +
	"\b_version\"<\n" +
	"\x10BackendsResponse\x12(\n" +
	"\bbackends\x18\x01 \x03(\v2\f.api.BackendR\bbackends\"C\n" +
	"\aInbound\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1b\n" +
	"\x06config\x18\x02 \x01(\tH\x00R\x06config\x88\x01\x01B\t\n" +
	"\a_config\"D\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"S\n" +
	"\bUserData\x12\x1d\n" +
	"\x04user\x18\x01 \x01(\v2\t.api.UserR\x04user\x12(\n" +
	"\binbounds\x18\x02 \x03(\v2\f.api.InboundR\binbounds\"9\n" +
	"\tUsersData\x12,\n" +
	"\n" +
	"users_data\x18\x01 \x03(\v2\r.api.UserDataR\tusersData\"}\n" +
	"\n" +
	"UsersStats\x12:\n" +
	"\vusers_stats\x18\x01 \x03(\v2\x19.api.UsersStats.UserStatsR\n" +
	"usersStats\x1a3\n" +
	"\tUserStats\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x14\n" +
	"\x05usage\x18\x02 \x01(\x04R\x05usage\"\x1d\n" +
	"\aLogLine\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\"m\n" +
	"\rBackendConfig\x12$\n" +
	"\rconfiguration\x18\x01 \x01(\tR\rconfiguration\x126\n" +
	"\rconfig_format\x18\x02 \x01(\x0e2\x11.api.ConfigFormatR\fconfigFormat\"^\n" +
	"\x12BackendLogsRequest\x12!\n" +
	"\fbackend_name\x18\x01 \x01(\tR\vbackendName\x12%\n" +
	"\x0einclude_buffer\x18\x02 \x01(\bR\rincludeBuffer\"v\n" +
	"\x15RestartBackendRequest\x12!\n" +
	"\fbackend_name\x18\x01 \x01(\tR\vbackendName\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x12.api.BackendConfigH\x00R\x06config\x88\x01\x01B\t\n" +
	"\a_config\"(\n" +
	"\fBackendStats\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning*-\n" +
	"\fConfigFormat\x12\t\n" +
	"\x05PLAIN\x10\x00\x12\b\n" +
	"\x04JSON\x10\x01\x12\b\n" +
	"\x04YAML\x10\x022\xae\x03\n" +
	"\vMarzService\x12(\n" +
	"\tSyncUsers\x12\r.api.UserData\x1a\n" +
	".api.Empty(\x01\x12-\n" +
	"\x0fRepopulateUsers\x12\x0e.api.UsersData\x1a\n" +
	".api.Empty\x122\n" +
	"\rFetchBackends\x12\n" +
	".api.Empty\x1a\x15.api.BackendsResponse\x12.\n" +
	"\x0fFetchUsersStats\x12\n" +
	".api.Empty\x1a\x0f.api.UsersStats\x126\n" +
	"\x12FetchBackendConfig\x12\f.api.Backend\x1a\x12.api.BackendConfig\x128\n" +
	"\x0eRestartBackend\x12\x1a.api.RestartBackendRequest\x1a\n" +
	".api.Empty\x12<\n" +
	"\x11StreamBackendLogs\x12\x17.api.BackendLogsRequest\x1a\f.api.LogLine0\x01\x122\n" +
	"\x0fGetBackendStats\x12\f.api.Backend\x1a\x11.api.BackendStatsB\rZ\vgrpc/api/pbb\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_service_proto_goTypes = []any{
	(ConfigFormat)(0),             // 0: api.ConfigFormat
	(*Empty)(nil),                 // 1: api.Empty
	(*Backend)(nil),               // 2: api.Backend
	(*BackendsResponse)(nil),      // 3: api.BackendsResponse
	(*Inbound)(nil),               // 4: api.Inbound
	(*User)(nil),                  // 5: api.User
	(*UserData)(nil),              // 6: api.UserData
	(*UsersData)(nil),             // 7: api.UsersData
	(*UsersStats)(nil),            // 8: api.UsersStats
	(*LogLine)(nil),               // 9: api.LogLine
	(*BackendConfig)(nil),         // 10: api.BackendConfig
	(*BackendLogsRequest)(nil),    // 11: api.BackendLogsRequest
	(*RestartBackendRequest)(nil), // 12: api.RestartBackendRequest
	(*BackendStats)(nil),          // 13: api.BackendStats
	(*UsersStats_UserStats)(nil),  // 14: api.UsersStats.UserStats
}
var file_proto_service_proto_depIdxs = []int32{
	4,  // 0: api.Backend.inbounds:type_name -> api.Inbound
	2,  // 1: api.BackendsResponse.backends:type_name -> api.Backend
	5,  // 2: api.UserData.user:type_name -> api.User
	4,  // 3: api.UserData.inbounds:type_name -> api.Inbound
	6,  // 4: api.UsersData.users_data:type_name -> api.UserData
	14, // 5: api.UsersStats.users_stats:type_name -> api.UsersStats.UserStats
	0,  // 6: api.BackendConfig.config_format:type_name -> api.ConfigFormat
	10, // 7: api.RestartBackendRequest.config:type_name -> api.BackendConfig
	6,  // 8: api.MarzService.SyncUsers:input_type -> api.UserData
	7,  // 9: api.MarzService.RepopulateUsers:input_type -> api.UsersData
	1,  // 10: api.MarzService.FetchBackends:input_type -> api.Empty
	1,  // 11: api.MarzService.FetchUsersStats:input_type -> api.Empty
	2,  // 12: api.MarzService.FetchBackendConfig:input_type -> api.Backend
	12, // 13: api.MarzService.RestartBackend:input_type -> api.RestartBackendRequest
	11, // 14: api.MarzService.StreamBackendLogs:input_type -> api.BackendLogsRequest
	2,  // 15: api.MarzService.GetBackendStats:input_type -> api.Backend
	1,  // 16: api.MarzService.SyncUsers:output_type -> api.Empty
	1,  // 17: api.MarzService.RepopulateUsers:output_type -> api.Empty
	3,  // 18: api.MarzService.FetchBackends:output_type -> api.BackendsResponse
	8,  // 19: api.MarzService.FetchUsersStats:output_type -> api.UsersStats
	10, // 20: api.MarzService.FetchBackendConfig:output_type -> api.BackendConfig
	1,  // 21: api.MarzService.RestartBackend:output_type -> api.Empty
	9,  // 22: api.MarzService.StreamBackendLogs:output_type -> api.LogLine
	13, // 23: api.MarzService.GetBackendStats:output_type -> api.BackendStats
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	file_proto_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_service_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		EnumInfos:         file_proto_service_proto_enumTypes,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
